"""Small demo server to serve SVG generated by Kernel GUI primitives."""
from fastapi import FastAPI, Response, Query
import uvicorn
from ..gui.nsbezier import NSBezierPath, sample_star, NSColor
from ..gui.nsbezier import NSPoint

app = FastAPI()

@app.get("/kernel/demo/svg")
def svg_demo(shape: str = Query('star'), width: int = Query(400), height: int = Query(400), stroke: str = Query('0,0,0'), fill: str = Query('255,215,0')):
    """Return an SVG generated from kernel primitives.

    shape: 'star'|'rect'|'oval'|'arc'
    stroke/fill: comma-separated RGB (e.g., 255,0,0)
    """
    def parse_color(s: str):
        parts = [int(p) for p in s.split(',')]
        r,g,b = parts[:3]
        return NSColor(r,g,b,1.0)

    stroke_color = parse_color(stroke)
    fill_color = None
    if fill:
        fill_color = parse_color(fill)

    if shape == 'star':
        p = sample_star(cx=width/2, cy=height/2, r1=min(width,height)/4, r2=min(width,height)/10)
    elif shape == 'rect':
        p = NSBezierPath()
        p.append_rect(50, 50, width-100, height-100)
    elif shape == 'oval':
        p = NSBezierPath()
        p.append_oval_in_rect(50, 50, width-100, height-100)
    elif shape == 'arc':
        p = NSBezierPath()
        p.append_arc(NSPoint(width/2, height/2), min(width,height)/4, 0, 3.14)
    else:
        p = sample_star(cx=width/2, cy=height/2, r1=min(width,height)/4, r2=min(width,height)/10)

    p.stroke(color=stroke_color)
    if fill_color:
        p.fill(fill_color)

    svg = p.to_svg(width=width, height=height)
    return Response(content=svg, media_type='image/svg+xml')

@app.get('/kernel/demo/html')
def html_demo():
    html = '''<!doctype html>
<html>
  <head><meta charset="utf-8"><title>Kernel SVG Demo</title></head>
  <body>
    <h3>Kernel 120: NSBezierPath demo</h3>
    <p>Try: <a href="/kernel/demo/svg?shape=star">star</a> | <a href="/kernel/demo/svg?shape=rect">rect</a> | <a href="/kernel/demo/svg?shape=oval">oval</a> | <a href="/kernel/demo/svg?shape=arc">arc</a></p>
    <img src="/kernel/demo/svg" alt="demo svg" />
  </body>
</html>'''
    return Response(content=html, media_type='text/html')

if __name__ == '__main__':
    # default dev server on 9009
    uvicorn.run('Kernel.demo.server:app', host='127.0.0.1', port=9009, log_level='info')
