"""Small demo server to serve SVG generated by Kernel GUI primitives.

Includes:
  /kernel/demo/svg       – shape SVG demo (star, rect, oval, arc)
  /kernel/demo/html      – landing page
  /kernel/demo/views     – interactive view-tree demo (click a view → event routed)
  /kernel/demo/event     – POST endpoint for events from the interactive demo
"""
from fastapi import FastAPI, Response, Query, Request
import uvicorn
import json
import time

from ..gui.nsbezier import NSBezierPath, sample_star, NSColor, NSPoint
from ..runtime.app import NSApplication
from ..runtime.event import NSEvent, NSEventType

app = FastAPI()

# ── original shape demo ───────────────────────────────────────────

@app.get("/kernel/demo/svg")
def svg_demo(shape: str = Query('star'), width: int = Query(400), height: int = Query(400),
             stroke: str = Query('0,0,0'), fill: str = Query('255,215,0')):
    """Return an SVG generated from kernel primitives."""
    def parse_color(s: str):
        parts = [int(p) for p in s.split(',')]
        r, g, b = parts[:3]
        return NSColor(r, g, b, 1.0)

    stroke_color = parse_color(stroke)
    fill_color = None
    if fill:
        fill_color = parse_color(fill)

    if shape == 'star':
        p = sample_star(cx=width / 2, cy=height / 2,
                        r1=min(width, height) / 4, r2=min(width, height) / 10)
    elif shape == 'rect':
        p = NSBezierPath()
        p.append_rect(50, 50, width - 100, height - 100)
    elif shape == 'oval':
        p = NSBezierPath()
        p.append_oval_in_rect(50, 50, width - 100, height - 100)
    elif shape == 'arc':
        p = NSBezierPath()
        p.append_arc(NSPoint(width / 2, height / 2), min(width, height) / 4, 0, 3.14)
    else:
        p = sample_star(cx=width / 2, cy=height / 2,
                        r1=min(width, height) / 4, r2=min(width, height) / 10)

    p.stroke(color=stroke_color)
    if fill_color:
        p.fill(fill_color)

    svg = p.to_svg(width=width, height=height)
    return Response(content=svg, media_type='image/svg+xml')


# ── interactive view-tree demo ────────────────────────────────────

_event_log = []  # last N events processed

def _build_demo_window():
    """Build a small demo view tree and return it as SVG + the window object."""
    from ..view.nsview import NSView, NSRect
    from ..window.nswindow import NSWindow

    win = NSWindow(content_rect=NSRect(0, 0, 500, 360), title="View Tree Demo")
    root = win.content_view
    root._background_color = NSColor(245, 245, 245)

    header = NSView(NSRect(10, 10, 480, 40))
    header._background_color = NSColor(70, 130, 220)
    header.identifier = "header"

    sidebar = NSView(NSRect(10, 60, 140, 280))
    sidebar._background_color = NSColor(220, 220, 240)
    sidebar.identifier = "sidebar"

    content = NSView(NSRect(160, 60, 330, 280))
    content._background_color = NSColor(255, 255, 255)
    content.identifier = "content"

    card1 = NSView(NSRect(10, 10, 150, 120))
    card1._background_color = NSColor(255, 220, 100)
    card1.identifier = "card-1"

    card2 = NSView(NSRect(170, 10, 150, 120))
    card2._background_color = NSColor(100, 220, 180)
    card2.identifier = "card-2"

    content.add_subview(card1)
    content.add_subview(card2)
    root.add_subview(header)
    root.add_subview(sidebar)
    root.add_subview(content)

    return win


@app.get("/kernel/demo/views")
def views_demo():
    """Interactive view-tree demo page."""
    win = _build_demo_window()
    svg = win.render_to_svg()
    log_html = ""
    for entry in _event_log[-10:]:
        log_html += f"<li>{entry}</li>"
    html = f'''<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Kernel 120 – View Tree Demo</title>
  <style>
    body {{ font-family: sans-serif; margin: 20px; }}
    svg {{ cursor: pointer; border: 1px solid #ccc; }}
    #log {{ max-height: 200px; overflow-y: auto; font-size: 13px; }}
    .info {{ color: #666; font-size: 13px; }}
  </style>
</head>
<body>
  <h3>Kernel 120: Interactive View Tree</h3>
  <p class="info">Click any colored region. The click coordinates are POSTed to the server,
  routed through NSApplication → NSWindow → hit-test → responder chain, and the
  result is shown below.</p>
  <div id="svg-container">{svg}</div>
  <h4>Event Log (server-side)</h4>
  <ul id="log">{log_html}</ul>
  <script>
    document.querySelector('#svg-container svg').addEventListener('click', async (e) => {{
      const rect = e.currentTarget.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      const resp = await fetch('/kernel/demo/event', {{
        method: 'POST',
        headers: {{'Content-Type': 'application/json'}},
        body: JSON.stringify({{x: x, y: y, type: 'MOUSE_DOWN'}})
      }});
      const data = await resp.json();
      const li = document.createElement('li');
      li.textContent = data.message;
      document.getElementById('log').prepend(li);
      // flash the hit view
      const hitEl = document.querySelector('[data-view-id="' + data.view_id + '"]');
      if (hitEl) {{
        const orig = hitEl.style.opacity;
        hitEl.style.opacity = '0.5';
        setTimeout(() => hitEl.style.opacity = orig || '1', 300);
      }}
    }});
  </script>
</body>
</html>'''
    return Response(content=html, media_type='text/html')


@app.post("/kernel/demo/event")
async def post_event(request: Request):
    """Receive a click event from the demo page, route through the view tree."""
    body = await request.json()
    x = float(body.get('x', 0))
    y = float(body.get('y', 0))
    event_type = body.get('type', 'MOUSE_DOWN')
    chrome_offset = 22  # title bar height

    win = _build_demo_window()
    ns_app = NSApplication()
    ns_app.set_main_responder(win)

    ev = NSEvent(
        type=NSEventType[event_type],
        location=(x, y - chrome_offset),
        timestamp=time.time(),
    )
    ns_app.post_event(ev)
    ns_app.run_once()

    hit = win.content_view.hit_test((x, y - chrome_offset))
    view_id = hit.identifier if hit else "none"
    view_repr = repr(hit) if hit else "none"

    msg = f"({x:.0f},{y:.0f}) → hit={view_id} {view_repr}"
    _event_log.append(msg)
    if len(_event_log) > 50:
        _event_log.pop(0)

    return {"message": msg, "view_id": view_id, "hit": view_repr}


# ── landing page ──────────────────────────────────────────────────

@app.get('/kernel/demo/html')
def html_demo():
    html = '''<!doctype html>
<html>
  <head><meta charset="utf-8"><title>Kernel SVG Demo</title></head>
  <body>
    <h3>Kernel 120: NSBezierPath demo</h3>
    <p>Try: <a href="/kernel/demo/svg?shape=star">star</a> |
           <a href="/kernel/demo/svg?shape=rect">rect</a> |
           <a href="/kernel/demo/svg?shape=oval">oval</a> |
           <a href="/kernel/demo/svg?shape=arc">arc</a></p>
    <p><strong><a href="/kernel/demo/views">Interactive View Tree Demo &rarr;</a></strong></p>
    <img src="/kernel/demo/svg" alt="demo svg" />
  </body>
</html>'''
    return Response(content=html, media_type='text/html')


if __name__ == '__main__':
    uvicorn.run('Kernel.demo.server:app', host='127.0.0.1', port=9009, log_level='info')
